### ISSUE TITLE
UBL LCD "Radar"

### ISSUE THREAD

**Issue by Tannoo** [Tannoo/Marlin#2]
@Roxy-3D, take a look... 10x10 matrix:
![radar 45](https://cloud.githubusercontent.com/assets/26955383/26127820/bc166724-3a47-11e7-9fc4-5193c10d4a82.jpg)
![radar 45 mapped](https://cloud.githubusercontent.com/assets/26955383/26127822/befe391c-3a47-11e7-90a5-dc204c4aedbf.jpg)

I have to set the coordinates first, then go map it.
Need to get encoder working to change the values dynamically.

**Comment by Roxy-3D** [comment]
Very cool!  And as you spin the encoder wheel...   It will sweep across a line, and then drop down to the next line?   If you click on a location, it could jump to the fine_tune_mesh() routine, edit the point, and then come back!

**Comment by Tannoo** [comment]
That's the idea. The encoder does jack atm.

**Comment by Tannoo** [comment]
So far, the code to do this is surprisingly small.

**Comment by Roxy-3D** [comment]
Look at how the fine_tune_mesh() uses the encoder wheel...  You should be able to 'Borrow very heavily' and just steal the encoder wheel logic:
```cpp
    static void _lcd_mesh_fine_tune(const char* msg) {
      defer_return_to_status = true;
      if (ubl.encoder_diff) {
        ubl_encoderPosition = (ubl.encoder_diff > 0) ? 1 : -1;
        ubl.encoder_diff = 0;

        mesh_edit_accumulator += float(ubl_encoderPosition) * 0.005 / 2.0;
        mesh_edit_value = mesh_edit_accumulator;
        encoderPosition = 0;
        lcdDrawUpdate = LCDVIEW_REDRAW_NOW;

        const int32_t rounded = (int32_t)(mesh_edit_value * 1000.0);
        mesh_edit_value = float(rounded - (rounded % 5L)) / 1000.0;
      }

      if (lcdDrawUpdate)
        lcd_implementation_drawedit(msg, ftostr43sign(mesh_edit_value));
    }
```

**Comment by Tannoo** [comment]
Yes, I was also looking at the babystepping section.

I have been getting some small details out of the way, like alignment of the box drawn and the handling of NAN's.
Now, trying to figure out how to dynamically set an offset for the box.
The encoder thing is pivotal (pun intended) on getting this to work. I just wanted to get some other 'loose' ends tied up instead of piling everything up and having a mess to straighten out.

**Comment by Roxy-3D** [comment]
Yeah...   Getting one piece working at a time is the best way.  That way when things don't work, you know where the problem is.    Some times you don't have a choice.  But when you have 1000 lines of code and none of it is tested and working...   You start pulling your hair out.

It would be cool if you could display a small x instead of a dot for any NAN.   That would make it real easy for people to fill in their mesh.   Or here is something else you may not have thought about.   For Delta's a lot of mesh points are off the bed (because they are outside the DELTA_PRINTABLE_RADIUS).   But the closest locations to mesh points that are still on the bed need to be filled in with reasonable values.   This is going to be the perfect tool to do that.  You just dial in the location that needs to be given a value, click, and give it a value.

**Comment by Tannoo** [comment]
Currently, I am displaying `Z: NAN` for those locations. I don't think there is room at that scale to put an `x` in the box.

Yes, I was thinking of drawing a circle over the box to represent the delta surface.
But, I am not familiar with delta code enough to find what I need to draw the correct size circle, unless I can base it on the GRID_MAX_POINTS_X and GRID_MAX_POINTS_Y.

But, Delta is going to have to wait. I would like to get this working for Cartesian first.

**Comment by Tannoo** [comment]
I have generated a 15x15 matrix for testing this also. Lemme get some screen shots of the NAN's I have in that.

**Comment by Tannoo** [comment]
>But when you have 1000 lines of code and none of it is tested and working... You start pulling your hair out.

That's no lie.

**Comment by Tannoo** [comment]
I do plenty of PLC programming. Same thing. C, C++, Aruduino... are WAAAAY different than PLC stuff.
But, can get just as bad on large projects. Especially if not commented.

**Comment by Roxy-3D** [comment]
One problem is the box might be harder to draw on a 20x4 LCD Display.  But if you made the box as big as possible, it is easier to show different stuff because you will have a few extra pixels to do things.   Hopefully we can make this work on a 20x4!

**Comment by Tannoo** [comment]
I'm not so sure about the 20x4. This may have to be limited to the graphic displays.

Unless you have some pixie dust lying around.  :P

**Comment by Tannoo** [comment]
I can make the box bigger. No problem.

**Comment by Tannoo** [comment]
This is using a 15x15 matrix:

![radar 22](https://cloud.githubusercontent.com/assets/26955383/26132236/27edb060-3a5c-11e7-8f9a-9709ba97d2c8.jpg)
![radar 22 mapped](https://cloud.githubusercontent.com/assets/26955383/26132237/293f51d0-3a5c-11e7-8ba8-45e01727fd40.jpg)

**Comment by Roxy-3D** [comment]
Even just leaving the text area blank for a NAN would be OK.  That would let people know there is not a number there yet...

**Comment by Tannoo** [comment]
M'kay

**Comment by Roxy-3D** [comment]
I didn't explain what I was thinking very well...   A blank field in the text (or number) box  is easy to figure out there is no number there.   But most users will not know what 'NAN' is.  Everyday there will be questions "What is NAN?"   "Why is it there?"

**Comment by Tannoo** [comment]
Yes, like I did.. lol

**Comment by Tannoo** [comment]
How about `Z: ---` so people don't think it's just not working?

**Comment by Roxy-3D** [comment]
That would be fine too...    Or even a question mark would work.    It's mostly NAN that I know is going to cause problems.

**Comment by Tannoo** [comment]
Changed it up a little.
![radar nan](https://cloud.githubusercontent.com/assets/26955383/26134409/abd3abd2-3a6b-11e7-8ac0-e712ea048f4a.jpg)

**Comment by Tannoo** [comment]
And again... This time, instead of the box being the grid boundaries, I've made it the printable boundary.

I'm still working out the math to get the grid points as accurate as possible.

**Comment by Roxy-3D** [comment]
If there is space on the screen...  It would be good to leave a pixel between the box and the point.   That would look nicer and be easier to see.     But with that said....  I do KNOW how hard it is to make this stuff actually work and then still appease everybody that have 'helpful ideas'.

**Comment by Tannoo** [comment]
Yes, there is space and that's the idea.

If I didn't tell you, math is not my strong point. lol

**Comment by Roxy-3D** [comment]
A much harder topic is this:   How do we make this map thing work on a 20x4 LCD Panel?   I'm wondering if we can do it with custom defined characters.

**Comment by Tannoo** [comment]
Oh God... I don't know.

Maybe, if I had one, I would try AFTER I get this working. lol

**Comment by Tannoo** [comment]
I had one, but I gave it to the grandkids with the printer I got them.

**Comment by Roxy-3D** [comment]
http://www.ebay.com/itm/2004-LCD-Display-Controller-w-Adapter-for-Ramps-1-4-3D-Printer-Mendel-Reprap-/351991203120?hash=item51f44f8530:g:gt4AAOSwzJ5Xa7Vi

I actually prefer the 20x4 over the Graphical display because it takes less CPU cycles to do its job.  You can feel the difference on the printer.   This map thingy is the first place where I would say "OK, the graphical display has an advantage."    But if we can get the 'right' custom characters defined...  I bet we can make it work on the 20x4 also.   Albeit...  You can see small 'dead zones' separating the characters on all sides.  We will just have to put up with that....

**Comment by Tannoo** [comment]
I know you keep pushing the 20x4 and Delta....Hold your horses.. lol They will get there. One thing at a time.

I'm currently just trying to get it to work a little different than originally planned. The graphic is what I have to write, test, debug, re-write, test, debug, test, re-write, test, debug,...etc.

**Comment by Tannoo** [comment]
If I was better at C AND math, this would go a little quicker. lol

**Comment by Roxy-3D** [comment]
> I know you keep pushing the 20x4 and Delta....Hold your horses.. lol They will get there. One thing at a time.

I do believe those both are important....   But I'm not pressuring you to do them.   Mostly, I'm just pointing out issues that if we can understand them fully now, it will be easier to deal with these items later.   I might be able to figure out how to make the custom characters that are needed and package up the support routines so you can just 'Plot' a point at the right spot.   What it would really do is just figure out the right character to put up in the correct location.

**Comment by Tannoo** [comment]
Yes.. I will be easier to get those items done, once I have at least one version working.

**Comment by Tannoo** [comment]
I still don't have the encoder stuff in there. lol

**Comment by Tannoo** [comment]
Changing the way the map is laid out, I believe would have been the biggest complaint. So, I'm changing it now.

**Comment by Tannoo** [comment]
The grid 0,0 looks good:
![00 mapped](https://cloud.githubusercontent.com/assets/26955383/26176006/e320e982-3b11-11e7-8663-fd451d978d00.jpg)

But, scaling is off for anything past that. This is grid 9,9.
![99 mapped](https://cloud.githubusercontent.com/assets/26955383/26176011/e56b6a14-3b11-11e7-8f25-bf6049d6669d.jpg)

This is currently my issue with this iteration.

**Comment by Tannoo** [comment]
The frame is:

`u8g.drawFrame(FRAME_X_OFFSET, FRAME_Y_OFFSET, (X_MAX_POS / 10), (Y_MAX_POS / 10));`

FRAME_X_OFFSET and FRAME_Y_OFFSET are for the screen placement and are figured from this (an effort to make this scalable):
```
      uint8_t FRAME_X_OFFSET = map(X_MAX_POS, 50, 400, 8, 5),
              FRAME_Y_OFFSET = map(Y_MAX_POS, 50, 400, 8, 5);
```

The pixel placement is this:
```
      uint8_t x_points = ((X_MAX_POS - (UBL_MESH_INSET * 2)) / GRID_MAX_POINTS_X) / 10;
      uint8_t y_points = ((Y_MAX_POS - (UBL_MESH_INSET * 2)) / GRID_MAX_POINTS_Y) / 10;

      u8g.drawPixel((x + (FRAME_X_OFFSET + 2) + UBL_MESH_INSET + (x_points * x)) / 2,
                    (y + (FRAME_Y_OFFSET + 2) + UBL_MESH_INSET + (y_points * y)) / 2);
```
Seems simple enough, but it don't quite do what I need it to do.

**Comment by Roxy-3D** [comment]
Obviously...  you are the one writing the code and get to do things your way...   But if it was me, I would consider making the box's area a multiple of what ever the number of grid points I'm trying to display.   So it is possible a 15 x 15 box would be different in size than an 11 x 13 box.   

The reason I would consider doing that is plotting the points becomes 'trivial'  (famous last words!).

But that does look very nice!  Did the encoder wheel move the point that was being displayed?  Or is that just hard coded right now?  Because it is showing up in a new location now.

**Comment by Tannoo** [comment]
Here is the full function so that it makes sense:

```
    void _lcd_ubl_plot_drawing(uint8_t x, uint8_t y) {
      // X_MAX_POS // Y_MAX_POS
      uint8_t FRAME_X_OFFSET = map(X_MAX_POS, 50, 400, 8, 5),
              FRAME_Y_OFFSET = map(Y_MAX_POS, 50, 400, 8, 5);

      // Show X and Y positions at top of screen
      u8g.setColorIndex(1);
      u8g.setPrintPos(5, 10);
      lcd_print("X:");
      lcd_print(ftostr32(LOGICAL_X_POSITION(pgm_read_float(&ubl.mesh_index_to_xpos[x]))));
      u8g.setPrintPos(70, 10);
      lcd_print("Y:");
      lcd_print(ftostr32(LOGICAL_X_POSITION(pgm_read_float(&ubl.mesh_index_to_ypos[y]))));

      // Draw box and location pixel
      u8g.setScale2x2();
      u8g.drawFrame(FRAME_X_OFFSET, FRAME_Y_OFFSET, (X_MAX_POS / 10), (Y_MAX_POS / 10));

      uint8_t x_points = ((X_MAX_POS - (UBL_MESH_INSET * 2)) / GRID_MAX_POINTS_X) / 10;
      uint8_t y_points = ((Y_MAX_POS - (UBL_MESH_INSET * 2)) / GRID_MAX_POINTS_Y) / 10;

      u8g.drawPixel((x + (FRAME_X_OFFSET + 2) + UBL_MESH_INSET + (x_points * x)) / 2,
                    (y + (FRAME_Y_OFFSET + 2) + UBL_MESH_INSET + (y_points * y)) / 2);

      // Show the Z value at right of frame
      u8g.undoScale();
      u8g.setPrintPos(66, 36);
        lcd_print("Z: ");
      if (!isnan(ubl.z_values[x][y])) {
        lcd_print(ftostr43sign(ubl.z_values[x][y]));
      }
      else {
        lcd_print("---");
      }
      // Show matrix size at bottom of screen
      u8g.setPrintPos(20, 60);
      lcd_print(itostr3(GRID_MAX_POINTS_X));
      lcd_print(" x");
      lcd_print(itostr3(GRID_MAX_POINTS_Y));
      lcd_print(" matrix");
    }
```

**Comment by Roxy-3D** [comment]
I wouldn't use the X & Y numbers...    I would use the x and y index numbers.  Because no matter what min and max x & y positions the user has...   The mesh index numbers still go from 0 upwards (to a max of 15).  It is still very easy to map an index to a real bed position if you want to display something.  That is done with    pgm_read_float(&mesh_index_to_xpos[ x_index ]))

OH!   I see you are already doing that!!!!    And I see how you are plotting the point's location...   I take back what I said about using indexes....  That is very simple and good!

**Comment by Tannoo** [comment]
The encoder is not in the picture yet. I'm an still setting the X and Y plot numbers.

I was just about to add the encoder when I decided to change the frame to be representative of the bed size and not the grid size.

**Comment by Tannoo** [comment]
Do you mean these: `ubl.mesh_index_to_ypos[x]` and `ubl.mesh_index_to_ypos[x]`?

**Comment by Tannoo** [comment]
Re-writing again... lol

np... but I am headed to work now.

**Comment by Tannoo** [comment]
>consider making the box's area a multiple of what ever the number of grid points I'm trying to display. So it is possible a 15 x 15 box would be different in size than an 11 x 13 box.

Well, this displays the box based on the Bed size not the probed grid size.
`u8g.drawFrame(FRAME_X_OFFSET, FRAME_Y_OFFSET, (X_MAX_POS / 10), (Y_MAX_POS / 10));`

**Comment by Tannoo** [comment]
I just defined this:
```
  #define GRID_MAX_POINTS_X 11      // Don't use more than 15 points per axis, implementation limited.
  #define GRID_MAX_POINTS_Y 13      //GRID_MAX_POINTS_X
```
Uploading now and will get two pics for you of 0,0 and of 9,9 on and 10x10 matrix.

**Comment by Roxy-3D** [comment]
And for sure...  We need 15 x 15 too!!!!

**Comment by Tannoo** [comment]
Change the frame (box) by changing the bed dimensions.

So, I changed this:
```
#define X_MAX_POS 400
#define Y_MAX_POS 185
```
and this:
```
  #define GRID_MAX_POINTS_X 11      // Don't use more than 15 points per axis, implementation limited.
  #define GRID_MAX_POINTS_Y 13      //GRID_MAX_POINTS_X
```

Let's see what we get.

**Comment by Tannoo** [comment]
It's a little extreme, but here are the pics for that config. I can't generate a mesh with that bed size.

```
Bed Topography Report for Excel:

0.129,0.298,NAN,0.289,0.259,-0.075,NAN,NAN,NAN,NAN,NAN
0.085,0.332,0.091,0.246,0.279,0.056,NAN,NAN,NAN,NAN,NAN
0.059,0.295,0.274,NAN,0.278,0.099,NAN,NAN,NAN,NAN,NAN
NAN,0.252,0.309,NAN,0.257,0.111,-0.592,NAN,NAN,NAN,NAN
NAN,0.216,0.352,0.066,0.238,0.139,-0.610,NAN,NAN,NAN,NAN
NAN,0.165,0.365,0.261,NAN,0.154,-0.573,NAN,NAN,NAN,NAN
NAN,NAN,0.326,0.341,NAN,0.183,-0.556,NAN,NAN,NAN,NAN
NAN,NAN,0.258,0.360,0.049,0.208,-0.504,NAN,NAN,NAN,NAN
NAN,0.112,0.212,0.375,0.238,NAN,-0.448,NAN,NAN,NAN,NAN
NAN,0.230,NAN,0.332,0.317,NAN,-0.369,NAN,NAN,NAN,NAN
NAN,0.225,NAN,0.294,0.345,0.012,-0.275,NAN,NAN,NAN,NAN
NAN,0.235,0.114,0.244,0.340,0.183,NAN,NAN,NAN,NAN,NAN
NAN,0.180,0.271,NAN,0.313,0.239,NAN,NAN,NAN,NAN,NAN
```

0,0 mapped
![test-00 mapped](https://cloud.githubusercontent.com/assets/26955383/26177707/11e107a6-3b18-11e7-9474-ac692df4b999.jpg)

10,12 (max)
![test-1012](https://cloud.githubusercontent.com/assets/26955383/26177812/881fa0bc-3b18-11e7-90fe-655a83576ea0.jpg)

10,12 mapped
![test-1012 mapped](https://cloud.githubusercontent.com/assets/26955383/26177785/67a24812-3b18-11e7-8300-a569919b071d.jpg)

**Comment by Roxy-3D** [comment]
I think I would argue the person knows the mesh size...  Maybe it would be better to put the Z: --- value down on that line and get it out of the way?

**Comment by Tannoo** [comment]
The `Z: ---` is not scaled. It will be later.

May also have to scale down a 400mm bed by 4 to make it fit better. This stuff will come later.

**Comment by Tannoo** [comment]
Okay.. I though about that also.

**Comment by Tannoo** [comment]
Would you want that box to represent the matrix size or the bed size?

**Comment by Tannoo** [comment]
I had it working better by matrix size...even scaled down to a 3x3. lol

**Comment by Roxy-3D** [comment]
I think if the box represented the matrix, it will be fine.  The person will see the dot move left and right.  And they will be able to count the number of dots until it drops down to the next line.    I would also consider 'scaling up' the size of the box depending on the mesh dimensions.  For example,  a 3 x 3 mesh box might be the same size as a 9 x 9.   But the dot jumps 3 times as far to get to the next one.   Mostly what I'm thinking is we are dealing with 'dots'...  The more we can space them out, especially for people with poor eye sight, the better.

**Comment by Tannoo** [comment]
Yes, ok... I'll work on that.

**Comment by Tannoo** [comment]
I do believe also that you are the master at 'food for thought'. Lol
