### ISSUE TITLE
Does this have anything to do with our recent merge?

### ISSUE THREAD

**Issue by Roxy-3D** [Tannoo/Marlin#8]
Does this have anything to do with our recent merge?  Technically, the code base is frozen but we (I) merged our stuff anyway...   If we broke something...  We better figure out how to fix it.

https://github.com/MarlinFirmware/Marlin/issues/7262

**Comment by Tannoo** [comment]
Yes, It did. I proposed the fix. I can't do much from my phone though.

Just make the ubl_lcd_map_control conditional for an lcd. That should fix it.

**Comment by Roxy-3D** [comment]
I'm out and about.   (It is a Friday night after all...   I always play darts on Friday nights....)   And when I get home, I won't dare do any code.   But if you make a fix I'll merge it in the morning.

The good news is...  Travis said everything was OK.   So, this is really just a small corner case.   Those people with the 128 KB boards need to spend $9 and get an ATMega-2560.

**Comment by Tannoo** [comment]
I change it in the morning then.

**Comment by Tannoo** [comment]
Here's my PR to fix it: #7265

**Comment by Tannoo** [comment]
I just got an MKS 3.2" touch display.

I am courious about the map there. Need movement buttons for it..and can move any direction due to that.

I should be able to use the DOGM code for the most part.

**Comment by Roxy-3D** [comment]
Yeah....   Movement buttons help a lot.   Right now, I have to spin the dial at the 'right' speed so that the nozzle doesn't go spastic when I'm trying to move from one row to the next.   If I had arrow buttons...  I could just click 5 times on the up and 2 times on the left.    I would rather have arrow buttons than an 'Encoder Wheel'.

**Comment by Tannoo** [comment]
Yeah... I found that this display is running smoothieware for it's 32-bit processor. So, I have to get familiar with smoothieware now. Lol

**Comment by Tannoo** [comment]
It's a little different than arduino.

**Comment by Bob-the-Kuhn** [comment]
My impression is the MKS 2.8" TFT is a host interface that bypasses the USB chip.

I didn't find anything useful about interfacing the 3.2" to anything.

----

Or is it that the 3.2" uses only 5V and the RAMPs system can't supply enough 5V power?

**Comment by Tannoo** [comment]
So far, I have read that the 3.2 doesn't have a way to input 12v on the ramps. I will see.

**Comment by Tannoo** [comment]
Initial testing with no modifications to the mks or marlin.
Plugged it into AUX1 (red stripe on 5v pin).
It powered up just fine.
Homing and moving any axis works correctly.
Leveling has something odd...didn't probe, but went to approx 30,30 and started lowering Z. It got too close for comfort and I hit the e-stop.

More testing is in order to see what I have to change in the display's fw settings.

**Comment by Roxy-3D** [comment]
I usually raise the Z axis up 150mm....  And then do a G28 and manually trigger the probe.    And then tell it to probe the entire bed (as I manually trigger the probe).   It is so easy to mess something up.   I need the time to press the reset button if the nozzle starts diving towards the bed.

**Comment by Tannoo** [comment]
Well, after a few minutes, the Arduino regulator didn't like 2powering 2 displays. Lol

I will suppliment the power like I did with the RGB strips.

**Comment by Tannoo** [comment]
So, @bob-the-kuhn, you were correct.

@Roxy-3d, I am going to do that next, but now I have to work my normal sceduled shift tonight and tomorrow.

This is going to be a long road. Don't expect too much too soon.

**Comment by Tannoo** [comment]
Powerwise, in the meantime, it's happier with a little help from the computer's usb connection.

**Comment by Roxy-3D** [comment]
> Yeah... I found that this display is running smoothieware for it's 32-bit processor. So, I have to get familiar with smoothieware now. Lol

Can you send me your house address?   (Or a shipping address at work is fine too!)   I think we might be getting a few 32-Bit Re-ARM boards.   And if you can be talked into it...  We need to make sure the LCD Panels are working with them.   Are you up for  a few head aches?

**Comment by Tannoo** [comment]
Sure, why not? It could fun! Maybe I can get that disco working that was mentioned (back when I first put out a PR for an RGB strip.

**Comment by Roxy-3D** [comment]
Well...  even the slow 32-bit boards are 5x faster than the AVR boards.   And there is plenty of memory to burn with the exception of EEPROM.   If the 'donation' happens, I'll make sure one of the boards gets sent to you.

**Comment by Tannoo** [comment]
Found a firmware to work and got some changes done.
Also changed some things in Marlin. PR coming soon.

https://youtu.be/k6CXJWqFYPU

**Comment by Roxy-3D** [comment]
Very cool!    Where did you get that touch screen?

**Comment by Tannoo** [comment]
I got it off Ebay. It's an MKS TFT32. The TFT28 has a power jack for 12v. The TFT32 does not.

**Comment by Tannoo** [comment]
It also looks like I have the source code... but, until I am able to compile it, I am not attempting to add screens yet.

I've changed a few images since that video.

**Comment by Tannoo** [comment]
I haven't tried printing from it's SD or USB yet.
