### ISSUE TITLE
MKS TFT32

### ISSUE THREAD

**Issue by Tannoo** [Tannoo/Marlin#9]
@Roxy-3D, I got that LCD [here ](http://www.ebay.com/itm/US-3-2-MKS-Touch-Screen-TFT32-LCD-Display-Controller-for-3D-Printer-Kit-RepRap/172659190494?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649)on Ebay.

**Comment by Tannoo** [comment]
New logo:
![20170713_101808](https://user-images.githubusercontent.com/26955383/28195457-8e79758e-6807-11e7-9217-18da1eaa56d3.jpg)

New button icons
![20170713_101819](https://user-images.githubusercontent.com/26955383/28195459-90869e56-6807-11e7-9a8d-aba40e81bf95.jpg)

**Comment by Roxy-3D** [comment]
Wow...  That looks nice...

**Comment by Tannoo** [comment]
I thought so. The logo needs some cleanup, though.

So, now that I have got customizing the images correct and working... on to trying to create more menus.
I applied the `M408` JSON responces PR (6970) to my Marlin and added a screen number for MOST screens in Marlin. I'm hoping to get the MKS to change based on the Marlin screen selected by another LCD. Basically, to stay 'on track' with what's currently happening.

But, I've got to figure out how to create other screens on the MKS.

**Comment by Tannoo** [comment]
So far, 62 possible screens.... I see a LOT of work in my future. LOL

**Comment by Tannoo** [comment]
I switch my printer back to the glcd and the ubl map is partly broken. I brought back a small part of previous code to make it work for me.

Take a look and see if you can fix what was broken.
I will post the code section a little later, if you don't have time to look for yourself.

It's the section that plots all the grid points in the box.

**Comment by Roxy-3D** [comment]
Which branch should I be looking at?   Can we just compare the code with the previously working stuff to find the error?

**Comment by Tannoo** [comment]
Yes, I did that.

**Comment by Tannoo** [comment]
Here's the code in question:
```
      // Display Mesh Point Locations
      uint8_t i, j;

      u8g.setColorIndex(1);
      for (i = 0; i < GRID_MAX_POINTS_X; i++) {
        for (j = 0; j < GRID_MAX_POINTS_Y; j++) {
          u8g.drawBox(x_offset+i * pixels_per_X_mesh_pnt + pixels_per_X_mesh_pnt / 2,  
                      y_offset+j * pixels_per_Y_mesh_pnt + pixels_per_Y_mesh_pnt / 2, 1, 1);
        }
      }

//      const uint8_t sx = x_offset + pixels_per_X_mesh_pnt / 2;
//            uint8_t  y = y_offset + pixels_per_Y_mesh_pnt / 2;
//      for (uint8_t j = 0; j < GRID_MAX_POINTS_Y; j++, y += pixels_per_Y_mesh_pnt)
//        if (PAGE_CONTAINS(y, y))
//          for (uint8_t i = 0, x = sx; i < GRID_MAX_POINTS_X; i++, x += pixels_per_X_mesh_pnt)
//            u8g.drawBox(sx, y, 1, 1);
```

**Comment by Tannoo** [comment]
The commented parts are in the current code base (bugfix-1.1.x). And all it does is put the mesh dots on the left column...no more.

The uncommented, is the previous code that works (On my printer now).

**Comment by Tannoo** [comment]
I am unsure how to correct the new code to work as before. I tried a few different things.

**Comment by Tannoo** [comment]
There's no real need to correct it now....the 32-bit stuff is more pressing.

**Comment by Tannoo** [comment]
I'm thinking it's in this line:
`for (uint8_t i = 0, x = sx; i < GRID_MAX_POINTS_X; i++, x += pixels_per_X_mesh_pnt)`.

**Comment by Roxy-3D** [comment]
I don't know what that line is going to do.   The reason is I don't know the order of evaluation of that stuff.   I don't like those complicated types of  code.   It is too hard to see what is happening.    It is also possible the PAGE_CONTAINS() macro isn't even allowing the loop to run...   It might be good to put those uncommented loops inside PAGE_CONTAINS()'s control to make sure the macro isn't errantly stopping the mesh points from being plotted.

**Comment by Tannoo** [comment]
ok.. I'll try that. BTW, I am switching to dayshift for 6 weeks.

**Comment by Roxy-3D** [comment]
There are a couple of small bugs in the Graphical LCD code on the 32-bit Re-ARM board.   I put your name very high on the list of people that should get Re-ARM boards.   And p3p has changed the default configuration of the Re-ARM branch to build with UBL turned on.     The LCD bug (with a selected menu item having the lines around it drawn wrong) probably doesn't need the board attached to a printer to get it fixed.   But the rest of the UBL LCD Menu stuff probably will need the board attached to a printer.

I don't know that this idea is practical.  But if you have a RAMPS based system, you might be able to just unplug one processor board and plug in the other.   That way, your printer wouldn't be non-functional when you actually want to use it to print something.   (In other words...  The RAMPS board never gets disconnected from the printer.  It is the processor board that gets disconnected from the RAMPS board.)

**Comment by Tannoo** [comment]
Is the 32-bit code printable atm?

**Comment by Roxy-3D** [comment]
I'm not sure...  But it is close.   The thing is, if you care about what you are trying to print, you probably don't want to use the 32-bit code yet.      But you can tell just from the LCD panel, it is close.

**Comment by Tannoo** [comment]
Ok. cool.

**Comment by Tannoo** [comment]
This was near the top of the DOGM file.
```
// For selective rendering within a Y range
#define PAGE_UNDER(yb) (u8g.getU8g()->current_page.y0 <= (yb))
#define PAGE_CONTAINS(ya, yb) (PAGE_UNDER(yb) && u8g.getU8g()->current_page.y1 >= (ya))
```

**Comment by Tannoo** [comment]
`PAGE_CONTAINS` is littered throughout the DOGM file.

**Comment by Tannoo** [comment]
I am soooo tired. I worked last night and am staying up all day to switch. I have to be at work WED morning.

**Comment by Roxy-3D** [comment]
OK!    Have a good night's sleep!

**Comment by Tannoo** [comment]
I can't sleep yet.... I have to stay up. At least 4 more hrs.

**Comment by Roxy-3D** [comment]
So did putting the simple loop code inside of a 
```cpp
   if (PAGE_CONTAINS(0,y_offset+(GRID_MAX_POINTS-1)*pixels_per_Y_mesh_pnt+pixels_per_Y_mesh_pnt/2 )) {
      // Display Mesh Point Locations
      uint8_t i, j;

      u8g.setColorIndex(1);
      for (i = 0; i < GRID_MAX_POINTS_X; i++) {
        for (j = 0; j < GRID_MAX_POINTS_Y; j++) {
          u8g.drawBox(x_offset+i * pixels_per_X_mesh_pnt + pixels_per_X_mesh_pnt / 2,  
                      y_offset+j * pixels_per_Y_mesh_pnt + pixels_per_Y_mesh_pnt / 2, 1, 1);
        }
      }
  }
```
work?  Because, if it did...  It is not the PAGE_CONTAINS() that is causing problem.  It is those complicated for() loops.

**Comment by Tannoo** [comment]
This:
```
      // Display Mesh Point Locations
      uint8_t  y = y_offset + pixels_per_Y_mesh_pnt / 2;
      if (PAGE_CONTAINS(y, y)) {
        uint8_t i, j;
        u8g.setColorIndex(1);
        for (i = 0; i < GRID_MAX_POINTS_X; i++) {
          for (j = 0; j < GRID_MAX_POINTS_Y; j++) {
            u8g.drawBox(x_offset+i * pixels_per_X_mesh_pnt + pixels_per_X_mesh_pnt / 2,  
                        y_offset+j * pixels_per_Y_mesh_pnt + pixels_per_Y_mesh_pnt / 2, 1, 1);
          }
        }
      }
```

Now has the mesh points plotted only along the top row.... nothing down any column.

**Comment by Roxy-3D** [comment]
Probably because you need something more like:
```cpp
   uint8_t  y = y_offset + (pixels_per_Y_mesh_pnt*(GRID_MAX_POINTS-1)) + pixels_per_Y_mesh_pnt / 2;

   if (PAGE_CONTAINS(0,y)  {
   }
```
The second parameter to PAGE_CONTAINS() is trying to see if the number is less than the max line on the page.

**Comment by Tannoo** [comment]
Alright....here's what made the new code work:
```
      u8g.setColorIndex(1);
      const uint8_t sx = x_offset + pixels_per_X_mesh_pnt / 2;
            uint8_t  y = y_offset + pixels_per_Y_mesh_pnt / 2;
      for (uint8_t j = 0; j < GRID_MAX_POINTS_Y; j++, y += pixels_per_Y_mesh_pnt)
        if (PAGE_CONTAINS(y, y))
          for (uint8_t i = 0, x = sx; i < GRID_MAX_POINTS_X; i++, x += pixels_per_X_mesh_pnt)
            u8g.drawBox(x, y, 1, 1);  <============= NEEDS TO PLOT X NOT SX!
```

**Comment by Tannoo** [comment]
Now all mesh points are plotted as it should be.

**Comment by Roxy-3D** [comment]
These simple bugs can cause hours of head aches....

**Comment by Tannoo** [comment]
Yes... I know. And both are a pain.

**Comment by Tannoo** [comment]
You can change it on the 32-bit side.
`ultralcd_impl_DOGM.h` Line 1004:
```
            u8g.drawBox(x, y, 1, 1);
```

**Comment by Tannoo** [comment]
I submitted PR 7310.

**Comment by Tannoo** [comment]
Back to the TFT...
I got the companion wifi adapter:
![wifi adapter](https://user-images.githubusercontent.com/26955383/28345203-e55e27f0-6be5-11e7-9a50-7ef03f3c33ac.jpg)

Setup my 5v regulator for the display:
![regulator assembly](https://user-images.githubusercontent.com/26955383/28345258-4a09fc42-6be6-11e7-8a0e-cbffb8077084.jpg)

Plugged it in, configured it in the display's config file, moved the config file to the display's SD and restarted the display. Went to the wifi info and waited for connection. No issues.
![wifi screen](https://user-images.githubusercontent.com/26955383/28345237-33dabbd2-6be6-11e7-9213-e9d80ab924c7.jpg)

Now, I installed and connected to it from my Android phone. Looks and works like Pronterface:
![phone app](https://user-images.githubusercontent.com/26955383/28345280-7122b7a6-6be6-11e7-9b94-c9ae2615a088.png)

This makes a second point of entry to my printer.. lol (Octopi being the first)

I have not tried to print from SD from the screen or the app. (supported by both)

**Comment by Tannoo** [comment]
The phone app works for everything on that screen, although, I cannot test the second extruder option.
The `PRINT` arrow take you to the SD file selection screen.

**Comment by Tannoo** [comment]
The regulator is getting awfully hot, even with the heat sink. I need a bigger regulator. I have not measured the current usage, but the display and the wifi unit are still running after 5 hrs of 83 deg ambient temp. I suspect it is adequate. I would like a little more 'wiggle' room though.

**Comment by Roxy-3D** [comment]
That does look like a nice interface to the printer!

**Comment by Tannoo** [comment]
This is another guy's project. I am looking to help with this.
I got my st-links in finally to get this project installed.

![20170722_172415](https://user-images.githubusercontent.com/26955383/28495182-d215efc8-6f02-11e7-8918-cf9bb600bba2.jpg)

**Comment by Tannoo** [comment]
Now, it's on to get the jist of this firmware.

**Comment by Tannoo** [comment]
It doesn't talk to Marlin yet.

**Comment by Tannoo** [comment]
I am ditching that display for now. I can't create new screens with that firmware. There is another project that I will have to get more familiar with to do that.

**Comment by Tannoo** [comment]
I've moved on to another display that is fully configurable and can write from scratch fairly easy.
